# Generated by Django 4.1 on 2024-04-20 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('brand', models.CharField(max_length=255)),
                ('country_code', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryCode', models.CharField(default=None, max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('country_name', models.TextField()),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='shopping.product')),
            ],
        ),
    ]
