# Generated by Django 4.1 on 2024-04-26 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0015_alter_product_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LineItem',
            new_name='CartItem',
        ),
    ]
